name: 'Checkout and run yarn install'
description: 'This action checks out the commit, sets up Node and installs deps using npm.'
author: 'henry'
inputs:
  fetch-depth:
    required: false
    description: 'Number of commits to fetch during checkout. 0 indicates all history for all branches and tags.'
    default: '1'
  fetch-ref:
    required: false
    description: 'Ref to fetch from'
    default: 'refs/heads/main'
  node-version:
    required: true
    description: 'Node version used for setup.'

runs:
  using: 'composite'