version: '3.1'
services:
  postgres:
    image: postgres:12
    container_name: pg_admin
    env_file: 
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    networks:
      - common
    volumes:
      - postgres_data:${PGDATA}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}

networks:
  common:

volumes:
  postgres_data: